repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
    - id: mypy
      additional_dependencies: ["sqlalchemy-stubs"]
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        "fideslib",
        "tests",
        "--disable=invalid-name",
        "--disable=line-too-long",
        "--disable=missing-class-docstring",
        "--disable=missing-module-docstring",
        "--disable=too-few-public-methods",
        "--disable=too-many-arguments",
        "--disable=too-many-instance-attributes",
        "--disable=unsubscriptable-object",
        "--disable=duplicate-code",
        "--ignore=fideslib.egg-info",
        "--extension-pkg-whitelist=pydantic",
        # "--rcfile=pyproject.toml",
        "-rn",  # Only display messages
        "-sn",  # Don't display score
      ]


      # disable=[
      #   "invalid-name",
      #   "line-too-long",
      #   "missing-class-docstring",
      #   "missing-module-docstring",
      #   "too-few-public-methods",
      #   "too-many-arguments",
      #   "too-many-instance-attributes",
      #   "unsubscriptable-object",
      # ]
      # ignore=[
      #   "fideslib.egg-info",
      # ]
      # extension-pkg-whitelist = "pydantic"
