services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    expose:
      - 5432
    ports:
      - "0.0.0.0:5432:5432"
