[database]
server = "localhost"
user = "postgres"
password = "postgres"
db = "test"
test_db = "test"

[security]
app_encryption_key = "OLMkv91j8DHiDAULnK5Lxx3kSCov30b3"
cors_origins = [
    "http://localhost",
    "http://localhost:8080",
    "http://localhost:3000",
    "http://localhost:3001",
]
encoding = "UTF-8"
oauth_root_client_id = "fidesadmin"
oauth_root_client_secret = "fidesadminsecret"
drp_jwt_secret = "secret"
