CREATE = "create"
CREATE_OR_UPDATE = "create_or_update"
DELETE = "delete"
READ = "read"
UPDATE = "update"

CLIENT = "client"
CLIENT_CREATE = f"{CLIENT}:{CREATE}"
CLIENT_DELETE = f"{CLIENT}:{DELETE}"
CLIENT_READ = f"{CLIENT}:{READ}"
CLIENT_UPDATE = f"{CLIENT}:{UPDATE}"

CONFIG_READ = f"config:{READ}"

POLICY = "policy"
POLICY_CREATE_OR_UPDATE = f"{POLICY}:{CREATE_OR_UPDATE}"
POLICY_DELETE = f"{POLICY}:{DELETE}"
POLICY_READ = f"{POLICY}:{READ}"

CONNECTION = "connection"
CONNECTION_CREATE_OR_UPDATE = f"{CONNECTION}:{CREATE_OR_UPDATE}"
CONNECTION_DELETE = f"{CONNECTION}:{DELETE}"
CONNECTION_READ = f"{CONNECTION}:{READ}"

PRIVACY_REQUEST = "privacy-request"
PRIVACY_REQUEST_CALLBACK_RESUME = (
    f"{PRIVACY_REQUEST}:resume"  # Permission to restart a paused privacy request
)
PRIVACY_REQUEST_CREATE = f"{PRIVACY_REQUEST}:{CREATE}"
PRIVACY_REQUEST_DELETE = f"{PRIVACY_REQUEST}:{DELETE}"
PRIVACY_REQUEST_READ = f"{PRIVACY_REQUEST}:{READ}"

WEBHOOK = "webhook"
WEBHOOK_CREATE_OR_UPDATE = f"{WEBHOOK}:{CREATE_OR_UPDATE}"
WEBHOOK_DELETE = f"{WEBHOOK}:{DELETE}"
WEBHOOK_READ = f"{WEBHOOK}:{READ}"

RULE = "rule"
RULE_CREATE_OR_UPDATE = f"{RULE}:{CREATE_OR_UPDATE}"
RULE_DELETE = f"{RULE}:{DELETE}"
RULE_READ = f"{RULE}:{READ}"

STORAGE = "storage"
STORAGE_CREATE_OR_UPDATE = f"{STORAGE}:{CREATE_OR_UPDATE}"
STORAGE_DELETE = f"{STORAGE}:{DELETE}"
STORAGE_READ = f"{STORAGE}:{READ}"

SCOPE_READ = f"scope:{READ}"

ENCRYPTION_EXEC = "encryption:exec"

DATASET = "dataset"
DATASET_CREATE_OR_UPDATE = f"{DATASET}:{CREATE_OR_UPDATE}"
DATASET_DELETE = f"{DATASET}:{DELETE}"
DATASET_READ = f"{DATASET}:{READ}"

# FIXME: Scope descriptions should be meaningful
SCOPE_DOCS = {
    CLIENT_CREATE: "test",
    CLIENT_UPDATE: "test",
    CLIENT_READ: "test",
    CLIENT_DELETE: "test",
    CONFIG_READ: "test",
    CONNECTION_READ: "test",
    CONNECTION_CREATE_OR_UPDATE: "test",
    CONNECTION_DELETE: "test",
    DATASET_CREATE_OR_UPDATE: "test",
    DATASET_DELETE: "test",
    DATASET_READ: "test",
    ENCRYPTION_EXEC: "test",
    POLICY_CREATE_OR_UPDATE: "test",
    POLICY_READ: "test",
    POLICY_DELETE: "test",
    PRIVACY_REQUEST_CREATE: "test",
    PRIVACY_REQUEST_READ: "test",
    PRIVACY_REQUEST_DELETE: "test",
    PRIVACY_REQUEST_CALLBACK_RESUME: "test",
    RULE_CREATE_OR_UPDATE: "test",
    RULE_READ: "test",
    RULE_DELETE: "test",
    SCOPE_READ: "test",
    STORAGE_CREATE_OR_UPDATE: "test",
    STORAGE_DELETE: "test",
    STORAGE_READ: "test",
    WEBHOOK_CREATE_OR_UPDATE: "test",
    WEBHOOK_READ: "test",
    WEBHOOK_DELETE: "test",
}

SCOPES = SCOPE_DOCS.keys()
