name: PR Checks

on:
  pull_request:
    branches:
      - main

env:
  CONTAINER: fideslib-local
  IMAGE: fideslib:local

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=/tmp/${{ env.CONTAINER }}.tar
          push: false
          tags: ${{ env.IMAGE }}

      - name: Upload container
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/${{ env.CONTAINER }}.tar
          retention-days: 1

  fidescls:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check package installation
        run: make check-install

  Black:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run formatter
        run: make black

  Pylint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        run: make pylint

  Mypy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run typechecker
        run: make mypy

  Xenon:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run cyclomatic complexity check
        run: make xenon

  Pytest:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidescls container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidescls image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test suite
        run: make pytest
