name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "21.8b0"

  Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run linter
        run: pylint --jobs=0 ./**

  Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run typechecker
        run: mypy --exclude 'setup\.py$' --ignore-missing-imports ./

  Xenon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run cyclomatic complexity check
        run: xenon ./ --max-absolute=B -max-modules=B --max-average=A

  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run unit test suite
        run: pytest
