name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Twine
        run: pip install twine

      - name: Twine Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist
          twine upload dist/*
